language: python
python:
  - '3.5'
  - '3.6'
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.6-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
cache:
  pip: true
  apt: true
before_install:
  - pip install codacy-coverage
  - wget https://github.com/BenLangmead/bowtie2/releases/download/v2.3.2/bowtie2-2.3.2-legacy-linux-x86_64.zip
  - unzip bowtie2-2.3.2-legacy-linux-x86_64.zip
  - export PATH=${PATH}:${PWD}/bowtie2-2.3.2-legacy
  - bowtie2 --version
install:
  pip install -r requirements.txt
script:
  pytest --db-host localhost
jobs:
  include:
  - stage: deploy
    python: 3.6
    script: echo "Deploy to PyPI"
    deploy:
      provider: pypi
      user: igboyes
      password: $PYPI_PWD
      on:
        branch: master
        tags: true
